[panel.server]
host = "127.0.0.1"
port = 8001
requests_separator = "%SEP%"

[panel.frontend]
port = 8002

[llm]
port = 8003
device = "cuda"
idle_time = inf

[llm.main_model]
model_path = "~/.swarmclone/llm/MiniLM2/MiniLM2-nGPT-0.4b-instruct"
model_id = "deepseek-chat"
model_source = "openai+https://api.deepseek.com" # 模型来源平台，如果以openai+开头则认为是openai风格的网络api，openai+后的内容被认为是openai的api地址
api_key = "PLACE HOLDER" # openai的api key
system_prompt = "你是一个名为知络的人工智能虚拟主播。你将与弹幕（以“【用户名】：【内容】”信息格式呈现）和你的开发者或其他主播（以“【用户名】：【内容】”信息格式呈现）进行互动。"
chat_role = "user" # MiniLM2有专门的弹幕角色
chat_template = "{user}：{content}"
asr_role = "user"
asr_template = "{user}：{content}"
stop_string = "\n\n\n"
temperature = 0.2

[llm.emotionclassification]
model_path = "~/.swarmclone/llm/EmotionClassification/SWCBiLSTM"
model_id = "MomoiaMoia/SWCBiLSTM"
model_source = "modelscope"

[asr]
port = 8004

[asr.sherpa]
model = "zipformer"
quantized = "fp32"
model_path = "~/.swarmclone/asr/"
decoding_method = "greedy_search"
provider = "cpu"
hotwords_file = ""
hotwords_score = 1.5
blank_penalty = 0.0
vadmodel_path = "~/.swarmclone/vad/"

[asr.userdb]
"DeveloperA" = "12345"

[tts]
port = 8005

[tts.cosyvoice]
sft_model = "CosyVoice-300M-SFT"
ins_model = "CosyVoice-300M-Instruct"
tune = "知络_1.2"
model_path = "~/.swarmclone/tts_cosy_voice"
float16 = true

[unity_frontend]
port = 8006

[chat]
port = 8007

[chat.bilibili]
live_room_id = 622909

[chat.bilibili.credential]
sessdata=""
bili_jct=""
buvid3=""
dedeuserid=""
ac_time_value=""
#credential参数的获取请参考 https://nemo2011.github.io/bilibili-api/#/get-credential
#获取完整弹幕信息仅需要sessdata

[playlist]
path="~/.swarmclone/playlist.json"

[chat.ncatbot]
target_group_id = "PLACE HOLDER" # QQ群号
bot_id = "PLACE HOLDER" # QQ机器人QQ号
root_id = "PLACE HOLDER" # 管理员QQ号
